language: php

matrix:
    include:
        - php: '5.6'
        - php: '7.0'

before_install: phpenv config-add travisconf.ini

before_script:
    - composer install

script:
    - bin/phpspec run
    - bin/phpunit

notifications:
  email:
    - franiglesias@mac.com
