language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0

before_script:
    - composer install

script:
    - bin/phpspec
    - bin/phpunit

notifications:
  email:
    - franiglesias@mac.com
    
