imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: services/management.yml }
    - { resource: services/contents.yml }
    - { resource: services/cantine.yml }
    - { resource: security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name:  '%session.name%'
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'foundation_5_layout.html.twig'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6.25
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Contents:
                type: annotation
                is_bundle: false
                dir: "%kernel.root_dir%/../src/Milhojas/Domain/Contents/DTO"
                prefix: Milhojas\Domain\Contents\DTO
                alias: Contents
            EventStore:
                type: annotation
                is_bundle: false
                dir: "%kernel.root_dir%/../src/Milhojas/Library/EventSourcing/DTO"
                prefix: Milhojas\Library\EventSourcing\DTO
                alias: EventStore
            StoreObject:
                type: annotation
                is_bundle: false
                dir: "%kernel.root_dir%/../tests/Library/EventSourcing/EventStore/Fixtures"
                prefix: Tests\Library\EventSourcing\EventStore\Fixtures
                alias: EventDouble
            Cantine:
                type: annotation
                is_bundle: false
                dir: "%kernel.root_dir%/../src/Milhojas/Domain/Cantine/DTO"
                prefix: Milhojas\Domain\Cantine\DTO
                alias: Cantine


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    antiflood:
        threshold:            35
        sleep:                30
    # spool:     { type: memory }
    # transport: gmail
    encryption: ssl
    auth_mode: login
    # spool:
    #   type: file
    #   path: "%kernel.root_dir%/../extras/spool"

# Configure the HWI BUndle to get authentication via Google Apps

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]
    http_client:
        verify_peer: true
    # an optional setting to configure a query string parameter which can be used to redirect
    # the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
    # redirect the user to /my/destination after facebook authenticates them.  If this is not
    # set then the user will be redirected to the original resource that they requested, or
    # the base address if no resource was requested.  This is similar to the behaviour of
    # [target_path_parameter for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html).
    # target_path_parameter: _destination

    # an optional setting to use the HTTP REFERER header to be used in case no
    # previous URL was stored in the session (i.e. no resource was requested).
    # This is similar to the behaviour of
    # [using the referring URL for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html#using-the-referring-url).
    # use_referer: true

    # here you will add one (or more) configurations for resource owners
    # and other settings you want to adjust in this bundle, just checkout the list below!

    # We will use Google Apps to authenticate
    # We need to update Google API > Credentials to allow the application
    resource_owners:
        google:
            type:                google
            client_id:           '%google.client_id%'
            client_secret:       '%google.client_secret%'
            scope:               "email profile"
            options:
                hd:     '%google.hd%'
                csrf:   false

# Uploader

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    storage: file_system

    mappings:
            payroll_file:
                uri_prefix:         /payroll/month
                upload_destination: '%upload_inbox%'
