doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   'pdo_mysql'
                host:     "localhost"
                port:     null
                dbname:   'milhojas'
                user:     'root'
                password: 'root'
                charset:  'utf8mb4'
                server_version: '5.6'
