# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    fran:
                        password: 123456
                        roles: 'ROLE_USER'
                    quino:
                        password: isa
                        roles: 'ROLE_ADMIN'
                        
        # Configure hwi as provider
        # Probably we need a custom user provider
        milhojas:
            id: milhojas.users.provider
            
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # configure firewall to use oauth
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    google:        "/login/check-google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                
                oauth_user_provider:
                    service: milhojas.users.provider
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
