# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    event_store:
        class:          Milhojas\Library\EventSourcing\EventStore\DoctrineEventStorage
        arguments:      ["@doctrine.orm.entity_manager"]
    post_repository:
        class:          Milhojas\Infrastructure\Persistence\Contents\EventSourcedPostRepository
        arguments:      ["@event_store"]
    handler_container:
        class:          Milhojas\Library\CommandBus\Containers\HandlerContainer
        arguments:      ["@service_container"]
    handler_inflector:
        class:          Milhojas\Library\CommandBus\Inflectors\HandlerInflector
    executer_bus_worker:
        class:          Milhojas\Library\CommandBus\Workers\ExecuteWorker
        arguments:      ["@handler_container", "@handler_inflector"]
    command_bus:
        class:          Milhojas\Library\CommandBus\BasicCommandBus
        arguments:      [["@executer_bus_worker"]]
# Contents Post Command Handlers
    write_post_handler:
        class:          Milhojas\Application\Contents\WritePostHandler
        arguments:      ["@post_repository"]
    update_post_handler:
        class:          Milhojas\Application\Contents\UpdatePostHandler
        arguments:      ["@post_repository"]

# Management Payroll Command Handlers
    finder:
        class:          Symfony\Component\Finder\Finder
    payroll_finder:
        class:          Milhojas\Infrastructure\Persistence\Management\PayrollFinder
        arguments:      ["@finder"]
    payroll_repository:
        class:          Milhojas\Infrastructure\Persistence\Management\FilePayrollRepository
        arguments:      ["%payroll.dataPath%", "@payroll_finder"]
    email_templating:
        class:          Milhojas\Infrastructure\Templating\Adapters\TwigTemplating
        arguments:      ['@twig']
    send_payroll_handler:
        class:          Milhojas\Application\Management\SendPayrollHandler
        arguments:      ['@payroll_repository', '@mailer', '@email_templating']
        
# Payroll dependencies
    payroll_send:
        class:          AppBundle\Command\Payroll\SendCommand
        arguments:      ["@mailer", "%payroll.sender%", "%payroll.report%", "%payroll.dataPath%"]
        tags:
             - {name: console.command}
    payroll_month:
        class:          AppBundle\Command\Payroll\MonthCommand
        arguments:      ["@mailer", "%payroll.sender%", "@command_bus", "%payroll.dataPath%"]
        tags:
             - {name: console.command}
        