# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    milhojas.property_descriptor:
        class:     Milhojas\Library\Mapper\Descriptor\PropertyDescriptor
    milhojas.object_mapper:
        class:          Milhojas\Library\Mapper\ObjectMapper
        arguments:      ["@milhojas.property_descriptor"]
    post_assembler:
        class:      Milhojas\Domain\Contents\PostAssembler
        arguments:  ["@milhojas.object_mapper"]
    post_repository:
        class:        Milhojas\Infrastructure\Persistence\Contents\DoctrinePostRepository
        arguments:    ["@doctrine.orm.entity_manager", '@post_assembler']

    handler_container:
        class:        Milhojas\Application\Containers\HandlerContainer
        arguments:    ["@service_container"]

    write_post_handler:
        class:        Milhojas\Application\Contents\WritePostHandler
        arguments:    ["@post_repository"]

