# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    event_store:
        class:          Milhojas\Library\EventSourcing\EventStore\DoctrineEventStorage
        arguments:      ["@doctrine.orm.entity_manager"]
    post_repository:
        class:          Milhojas\Infrastructure\Persistence\Contents\EventSourcedPostRepository
        arguments:      ["@event_store"]
    handler_container:
        class:          Milhojas\Library\CommandBus\Containers\HandlerContainer
        arguments:      ["@service_container"]
    handler_inflector:
        class:          Milhojas\Library\CommandBus\Inflectors\HandlerInflector
    executer_bus_worker:
        class:          Milhojas\Library\CommandBus\Workers\ExecuteWorker
        arguments:      ["@handler_container", "@handler_inflector"]
    command_bus:
        class:          Milhojas\Library\CommandBus\BasicCommandBus
        arguments:      [["@executer_bus_worker"]]
# Contents Post Command Handlers
    write_post_handler:
        class:          Milhojas\Application\Contents\WritePostHandler
        arguments:      ["@post_repository"]
    update_post_handler:
        class:          Milhojas\Application\Contents\UpdatePostHandler
        arguments:      ["@post_repository"]

# Mailer
    milhojas.templating.engine:
        class:          Milhojas\Infrastructure\Templating\Adapters\TwigTemplating
        arguments:      ['@twig']
    milhojas.mailer.engine:
        class:          Milhojas\Infrastructure\Mail\Adapters\SwiftMailerEngineAdapter
        arguments:      ['@mailer']
    milhojas.mailer.basic:
        class:          Milhojas\Infrastructure\Mail\Mailers\BasicMailer
        arguments:      ['@milhojas.mailer.engine']
    milhojas.mailer:
        class:          Milhojas\Infrastructure\Mail\Mailers\TemplateMailer
        arguments:      ['@milhojas.mailer.basic', '@milhojas.templating.engine']

# Management Payroll Command Handlers
    finder:
        class:          Symfony\Component\Finder\Finder
    milhojas.payroll.finder:
        class:          Milhojas\Infrastructure\Persistence\Management\PayrollFinder
        arguments:      ["@finder"]
    milhojas.payroll.dataparser:
        class:          Milhojas\Infrastructure\Utilities\TabDataParser
        arguments:      [['id', 'email', 'gender']]
    milhojas.payroll.repository:
        class:          Milhojas\Infrastructure\Persistence\Management\FilePayrollRepository
        arguments:      ["%payroll.dataPath%", "@milhojas.payroll.finder", "@milhojas.payroll.dataparser"]
    send_payroll_handler:
        class:          Milhojas\Application\Management\SendPayrollHandler
        arguments:      ['@milhojas.payroll.repository', '@milhojas.mailer']
        
# Payroll command
    payroll_month:
        class:          AppBundle\Command\Payroll\MonthCommand
        arguments:      ["%payroll.sender%", "@command_bus"]
        tags:
             - {name: console.command}
    
    it.report_device_status:
        class:          Milhojas\Application\It\ReportDeviceStatus
        arguments:      ['@milhojas.mailer', '%device.sender%', '%device.report%']
             
# EventBus
    event_bus:
        class:          Milhojas\Library\EventBus\SimpleEventBus
        calls:
            # - ['addHandler', ['milhojas.it.device_was_ok', '@it.report_device_status']]
            - ['addHandler', ['milhojas.it.device_ran_out_of_supplies', '@it.report_device_status']]
            

# It Command Handlers
    device_monitor:
        class:          Milhojas\Domain\It\DeviceMonitor
    event_recorder:
        class:          Milhojas\Library\EventBus\EventRecorder
    monitor_devices_handler:
        class:          Milhojas\Application\It\MonitorDevicesHandler
        arguments:      ["@device_monitor", "@event_recorder"]
        
    event_command_bus:
        class:          Milhojas\Library\CommandBus\EventAwareCommandBus
        arguments:      [["@executer_bus_worker"], '@event_bus', '@event_recorder']
# It Monitor command
    it_monitor:
        class:          AppBundle\Command\It\MonitorCommand
        arguments:      ["@event_command_bus", "@event_recorder"]
        tags:
            - {name: console.command}
        