services:
    post_repository:
        class:          Milhojas\Infrastructure\Persistence\Contents\EventBasedPostRepository
        arguments:      ["@event_sourcing_repository"]

# Contents Post Command Handlers
    contents.write_post.handler:
        class:          Milhojas\Application\Contents\Command\WritePostHandler
        arguments:      ["@post_repository", "@event_recorder"]
    contents.update_post.handler:
        class:          Milhojas\Application\Contents\Command\UpdatePostHandler
        arguments:      ["@post_repository", "@event_recorder"]

    contents.post_created.reporter:
        class:          Milhojas\Application\Contents\Reporter\NewPostWasWrittenReporter
        arguments:      ['@milhojas.mailer', '%contents.sender%', '%contents.report%', 'AppBundle:Contents:post.created.email.twig']

    contents.post_updated.reporter:
        class:          Milhojas\Application\Contents\Reporter\PostWasUpdatedReporter
        arguments:      ['@milhojas.mailer', '%contents.sender%', '%contents.report%', 'AppBundle:Contents:post.updated.email.twig']

    contents.post_list.projector:
        class:          Milhojas\Application\Contents\Projector\PostListProjector
        arguments:      ["@doctrine.orm.entity_manager"]
