parameters:
#    parameter_name: value
# Groups of related events for subscribers
  milhojas.it.monitor.email.events:
      - 'milhojas.it.device_ran_out_of_supplies'
      - 'milhojas.it.device_failed'
      - 'milhojas.it.device_stopped_listening'
      - 'milhojas.it.device_went_down'
  milhojas.it.monitor.all.events:
      - 'milhojas.it.device_ran_out_of_supplies'
      - 'milhojas.it.device_failed'
      - 'milhojas.it.device_stopped_listening'
      - 'milhojas.it.device_went_down'
      - 'milhojas.it.device_was_ok'

services:
    it.device_status.email.reporter:
        class:          Milhojas\Application\It\Reporters\DeviceStatusEmailReporter
        arguments:      ['@milhojas.mailer', '%device.sender%', '%device.report%', 'AppBundle:It:device.email.twig']
        
    it.device_status.cli.reporter:
        class:          Milhojas\Application\It\Reporters\DeviceStatusCliReporter
        arguments:      ['@cli.output']

# It Command Handlers
    device_monitor:
        class:          Milhojas\Domain\It\DeviceMonitor
        
    monitor_devices_handler:
        class:          Milhojas\Application\It\MonitorDevicesHandler
        arguments:      ["@device_monitor", "@event_recorder"]
        
# It Monitor command
    it_monitor:
        class:          AppBundle\Command\It\MonitorCommand
        arguments:      ["@command_bus"]
        tags:
            - {name: console.command}
