parameters:
    payroll.sender:
        administracion@miralba.org: 'Administración Colegio Miralba'
    payroll.report:
        administracion@miralba.org: 'Administración Colegio Miralba'
        webmaster@miralba.org: 'Webmaster'
    payroll.dataPath: '%upload_inbox%'
    payroll.email.template: 'AppBundle:Management:payroll_document.email.twig'

services:

    # Reporters

    management.payroll_was_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporter\PayrollWasSentCliReporter
        arguments:      ['@cli.output']

    management.payroll_could_not_be_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporter\PayrollCouldNotBeSentCliReporter
        arguments:      ['@cli.output']

    management.all_payrolls_were_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporter\AllPayrollsWereSentCliReporter
        arguments:      ['@cli.output']

    management.email_was_not_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporter\PayrollWasNotSentCliReporter
        arguments:      ['@cli.output']

    management.payroll_reporter_exchange:
        class:          Milhojas\Application\Management\PayrollProgressExchange
        arguments:      ['management-payroll-reporter.json', '@local_exchange.fs']

    management.payroll_sending_complete.reporter:
        class:          Milhojas\Application\Management\Listener\PayrollSendingCompleteReporter
        arguments:      ['no-payroll-found.data', '@local_exchange.fs', '@milhojas.mailer', '%payroll.sender%', '%payroll.report%', 'AppBundle:Management:payroll.completed.email.twig']

    management.payroll_progress.reporter:
        class:          Milhojas\Application\Management\Reporter\PayrollProgressReporter
        arguments:      ['management-payroll-reporter.json', '@local_exchange.fs']

    management.payroll_progress.resetter:
        class:          Milhojas\Application\Management\Listener\ResetPayrollProgress
        arguments:      ['@management.payroll_reporter_exchange']

    management.register_employee_without_payroll.listener:
        class:          Milhojas\Application\Management\Listener\RegisterEmployeeWithoutPayroll
        arguments:      ['no-payroll-found.data', '@local_exchange.fs']

    # Repositories

    management.staff:
        class:          Milhojas\Infrastructure\Persistence\Management\YamlStaff
        arguments:      ['%staff.file%']

    management.payrolls:
        class:          Milhojas\Infrastructure\Persistence\Management\ZipPayrolls
        arguments:      ["%payroll.dataPath%"]

    # Command Handlers

    management.send_payroll.handler:
        class:          Milhojas\Application\Management\Command\SendPayrollHandler
        arguments:      ['@management.payrolls', '%payroll.email.template%', '@milhojas.mailer',  "@event_recorder"]

    management.distribute_payroll.handler:
        class:          Milhojas\Application\Management\Command\DistributePayrollHandler
        arguments:      ['@management.staff', '%payroll.sender%', '@command_bus', '@logger']
        tags:
            - { name: monolog.logger, channel: messageBus }

    management.launch_payroll_distributor.handler:
        class:          Milhojas\Application\Management\Command\LaunchPayrollDistributorHandler


    management.start_payroll.handler:
        class:          Milhojas\Application\Management\Command\StartPayrollHandler
        arguments:      ['@management.payroll_reporter_exchange', '@event_recorder']
    management.end_payroll.handler:
        class:          Milhojas\Application\Management\Command\EndPayrollHandler
        arguments:      ['@event_recorder']


# Payroll command
    payroll_month:
        class:          AppBundle\Command\Payroll\MonthCommand
        arguments:      ["@command_bus"]
        tags:
            - {name: console.command}
