parameters:
    payroll.sender:
        administracion@miralba.org: 'Administración Colegio Miralba'
    payroll.report:
        administracion@miralba.org: 'Administración Colegio Miralba'
        webmaster@miralba.org: 'Webmaster'
    payroll.dataPath: '%uploads.inbox%'
    payroll.email.template: 'AppBundle:Management:payroll_document.email.twig'

services:

    clibuilder:
        class:          Milhojas\Infrastructure\Process\CommandLineBuilder

    # Reporters

    management.payroll_was_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporter\PayrollWasSentCliReporter
        arguments:      ['@cli.output']

    management.payroll_could_not_be_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporter\PayrollCouldNotBeSentCliReporter
        arguments:      ['@cli.output']

    management.all_payrolls_were_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporter\AllPayrollsWereSentCliReporter
        arguments:      ['@cli.output']

    management.email_was_not_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporter\PayrollWasNotSentCliReporter
        arguments:      ['@cli.output']

    management.payroll_reporter_exchange:
        class:          Milhojas\Application\Management\PayrollProgressExchange
        arguments:      ['management-payroll-reporter.json', '@local_exchange.fs']

    management.payroll_sending_complete.reporter:
        class:          Milhojas\Application\Management\Listener\PayrollSendingCompleteReporter
        arguments:      ['no-payroll-found.data', '@local_exchange.fs', '@milhojas.mailer', '%payroll.sender%', '%payroll.report%', 'AppBundle:Management:payroll.completed.email.twig']

    management.payroll_progress.reporter:
        class:          Milhojas\Application\Management\Reporter\PayrollProgressReporter
        arguments:      ['management-payroll-reporter.json', '@local_exchange.fs']

    management.payroll_progress.resetter:
        class:          Milhojas\Application\Management\Listener\ResetPayrollProgress
        arguments:      ['@management.payroll_reporter_exchange']

    management.register_employee_without_payroll.listener:
        class:          Milhojas\Application\Management\Listener\RegisterEmployeeWithoutPayroll
        arguments:      ['no-payroll-found.data', '@local_exchange.fs']

    management.init_progress_exchange.listener:
        class:          Milhojas\Application\Management\Listener\InitProgressExchange
        arguments:      ['@management.payroll_reporter_exchange']


    management.archive_sent_payrolls.listener:
        class:          Milhojas\Application\Management\Listener\ArchiveSentPayrolls
        arguments:      ['@management.payrolls']

    management.report_unsent_payrolls.listener:
        class:          Milhojas\Application\Management\Listener\ReportUnsentPayrolls
        arguments:      ['@inbox.fs', '@milhojas.mailer', '%payroll.sender%', '%payroll.report%', 'AppBundle:Management:payroll_unsent.email.twig']

    management.log_events.listener:
        class:          Milhojas\Application\Management\Listener\LogPayrollEvent
        arguments:      ['@logger']
        tags:
            - { name: monolog.logger, channel: dispatcher }


    # Repositories

    management.staff:
        class:          Milhojas\Infrastructure\Persistence\Management\YamlStaff
        arguments:      ['%staff.file%']

    management.payrolls:
        class:          Milhojas\Infrastructure\Persistence\Management\VirtualFSPayrolls
        arguments:      ["@inbox.fs", "@inbox.manager", '@filesystem.factory' ]

    # Command Handlers

    management.send_payroll.handler:
        class:          Milhojas\Application\Management\Command\SendPayrollHandler
        arguments:      ['@management.payrolls', '%payroll.email.template%', '%payroll.sender%', '@milhojas.mailer',  "@event_bus"]

    management.distribute_payroll.handler:
        class:          Milhojas\Application\Management\Command\DistributePayrollHandler
        arguments:      ['@management.staff', '@management.payrolls', '@command_bus', '@event_bus']

    management.launch_payroll_distributor.handler:
        class:          Milhojas\Application\Management\Command\LaunchPayrollDistributorHandler
        arguments:      ['@clibuilder']

# Payroll command
    payroll_month:
        class:          AppBundle\Command\Payroll\MonthCommand
        arguments:      ["@command_bus"]
        tags:
            - {name: console.command}
