parameters:
    payroll.sender:
        administracion@miralba.org: 'Administración Colegio Miralba'
    payroll.report:
        administracion@miralba.org: 'Administración Colegio Miralba'
        webmaster@miralba.org: 'Webmaster'
    payroll.dataPath: '%kernel.root_dir%/../extras/inbox'
    payroll.email.template: 'AppBundle:Management:payroll_document.email.twig'

services:

    # Reporters
    
    management.payroll_was_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporters\PayrollWasSentCliReporter
        arguments:      ['@cli.output']

    management.payroll_could_not_be_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporters\PayrollCouldNotBeSentCliReporter
        arguments:      ['@cli.output']

    management.all_payrolls_were_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporters\AllPayrollsWereSentCliReporter
        arguments:      ['@cli.output']


    management.email_was_not_sent.cli.reporter:
        class:          Milhojas\Application\Management\Reporters\PayrollWasNotSentCliReporter
        arguments:      ['@cli.output']

    management.email_report_all_payrolls_were_sent:
        class:          Milhojas\Application\Management\Reporters\AllPayrollsWereSentEmailReporter
        arguments:      ['@milhojas.mailer', '%payroll.sender%', '%payroll.report%', 'AppBundle:Management:all_payrolls.sent.email.twig']

    management.payroll_progress.reporter:
        class:          Milhojas\Application\Management\Reporters\PayrollProgressReporter
        arguments:      ['var/exchange/management-payroll-reporter.json']
        
    management.payroll_progress.resetter:
        class:          Milhojas\Application\Management\Handlers\ResetPayrollProgress
        arguments:      ['var/exchange/management-payroll-reporter.json']

    # Repositories

    management.staff:
        class:          Milhojas\Infrastructure\Persistence\Management\YamlStaff
        arguments:      ['%staff.file%']

    management.payrolls:
        class:          Milhojas\Infrastructure\Persistence\Management\ZipPayrolls
        arguments:      ["%payroll.dataPath%"]

    # Command Handlers

    send_payroll_handler:
        class:          Milhojas\Application\Management\Commands\SendPayrollHandler
        arguments:      ['@management.payrolls', '%payroll.email.template%', '@milhojas.mailer',  "@event_recorder"]
    
    distribute_payroll_handler:
        class:          Milhojas\Application\Management\Commands\DistributePayrollHandler
        arguments:      ['@management.staff', '%payroll.sender%', '@command_bus']
    

# Payroll command
    payroll_month:
        class:          AppBundle\Command\Payroll\MonthCommand
        arguments:      ["@command_bus"]
        tags:
            - {name: console.command}
