parameters:
    payroll.sender:
        administracion@miralba.org: 'Administración Colegio Miralba'
    payroll.report:
        administracion@miralba.org: 'Administración Colegio Miralba'
        webmaster@miralba.org: 'Webmaster'
    payroll.dataPath: '%kernel.root_dir%/../payroll'

services:

    management.payroll.finder:
        class:          Milhojas\Infrastructure\Persistence\Management\PayrollFinder
        arguments:      ["@finder"]
    management.payroll.dataparser:
        class:          Milhojas\Infrastructure\Utilities\TabDataParser
        arguments:      [['id', 'email', 'gender', 'name', 'last']]
    management.payroll.repository:
        class:          Milhojas\Infrastructure\Persistence\Management\FilePayrollRepository
        arguments:      ["%payroll.dataPath%", "@management.payroll.finder", "@management.payroll.dataparser"]

    send_payroll_handler:
        class:          Milhojas\Application\Management\SendPayrollHandler
        arguments:      ['@management.payroll.repository', '@milhojas.mailer',  "@event_recorder"]

    email_payroll_handler:
        class:          Milhojas\Application\Management\EmailPayrollHandler
        arguments:      ['@milhojas.mailer',  "@event_recorder"]

    management.payroll_was_sent.cli.reporter:
        class:          Milhojas\Application\Management\CliReportPayrollWasSent
        arguments:      ['@cli.output']

    management.payroll_could_not_be_sent.cli.reporter:
        class:          Milhojas\Application\Management\CliReportPayrollCouldNotBeSent
        arguments:      ['@cli.output']

    management.email_report_all_payrolls_were_sent:
        class:          Milhojas\Application\Management\Reporters\AllPayrollsWereSentEmailReporter
        arguments:      ['@milhojas.mailer', '%payroll.sender%', '%payroll.report%', 'AppBundle:Management:all_payrolls.sent.email.twig']

# Payroll command
    payroll_send:
        class:          AppBundle\Command\Payroll\SendCommand
        arguments:      ["@command_bus", "%payroll.sender%", '@management.payroll.repository']
        tags:
            - {name: console.command}
