services:
    student_repository:
        class:  Milhojas\Infrastructure\Persistence\Shared\StudentServiceDoctrineRepository
        arguments: ['@doctrine.orm.entity_manager']
    shared.enroll_student.handler:
        class:  Milhojas\Application\Shared\Command\EnrollStudentHandler
        arguments:  ['@student_repository', '@event_recorder']

    shared.get_all_enrolled_students.handler:
        class:  Milhojas\Application\Shared\Query\GetAllEnrolledStudentsHandler
        arguments:  ['@student_repository']
